import React from "react";

export const metadata = {
  title: "Ali sila",
  description: "Generated by create next app",
};

const layout = ({ children }) => {
  return <div className="bg-yellow-300">{children}</div>;
};

export default layout;
